# coding: utf-8

"""
    Flavorite - OpenAPI 3.0

    This is a Flavorite Server based on the OpenAPI 3.0 specification. 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from fastapi import FastAPI

from openapi_server.apis.restaurants_api import router as RestaurantsApiRouter
from openapi_server.apis.reviews_api import router as ReviewsApiRouter
from openapi_server.apis.users_api import router as UsersApiRouter

app = FastAPI(
    title="Flavorite - OpenAPI 3.0",
    description="This is a Flavorite Server based on the OpenAPI 3.0 specification. ",
    version="1.0.0",
)

app.include_router(RestaurantsApiRouter)
app.include_router(ReviewsApiRouter)
app.include_router(UsersApiRouter)
