# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class Restaurant(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Restaurant - a model defined in OpenAPI

        id: The id of this Restaurant [Optional].
        name: The name of this Restaurant [Optional].
        longitude: The longitude of this Restaurant [Optional].
        latitude: The latitude of this Restaurant [Optional].
        address: The address of this Restaurant [Optional].
    """

    id: Optional[int] = Field(alias="id", default=None)
    name: Optional[str] = Field(alias="name", default=None)
    longitude: Optional[float] = Field(alias="longitude", default=None)
    latitude: Optional[float] = Field(alias="latitude", default=None)
    address: Optional[str] = Field(alias="address", default=None)

Restaurant.update_forward_refs()
