# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, EmailStr, Field, validator  # noqa: F401
from fastapi_camelcase import CamelModel


class FavoriteFood(CamelModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    FavoriteFood - a model defined in OpenAPI

        id: The id of this FavoriteFood.
        name: The name of this FavoriteFood.
    """

    id: int = Field(alias="id")
    name: str = Field(alias="name")


FavoriteFood.update_forward_refs()
