# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, EmailStr, Field, validator  # noqa: F401
from fastapi_camelcase import CamelModel
from openapi_server.models.user import User


class ListFriends(CamelModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ListFriends - a model defined in OpenAPI

        friends: The friends of this ListFriends.
        fb_connected: The fb_connected of this ListFriends [Optional].
    """

    friends: List[User] = Field(alias="friends")
    fb_connected: Optional[bool] = Field(alias="fbConnected", default=None)


ListFriends.update_forward_refs()
