# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.restaurant import Restaurant


class ListRestaurants(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ListRestaurants - a model defined in OpenAPI

        restaurants: The restaurants of this ListRestaurants.
    """

    restaurants: List[Restaurant] = Field(alias="restaurants")

ListRestaurants.update_forward_refs()
