# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.user import User


class ListFriends(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ListFriends - a model defined in OpenAPI

        friends: The friends of this ListFriends.
    """

    friends: List[User] = Field(alias="friends")


ListFriends.update_forward_refs()
