# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, EmailStr, Field, validator  # noqa: F401
from fastapi_camelcase import CamelModel


class LoginPayload(CamelModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    LoginPayload - a model defined in OpenAPI

        token: The token of this LoginPayload.
        username: The username of this LoginPayload.
    """

    token: str = Field(alias="token")
    username: str = Field(alias="username")


LoginPayload.update_forward_refs()
